testing role assume

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -1,7 +1,7 @@
 on:
   push:
     branches:
-      - master
+      - main
 
 name: Deploy to Amazon ECS
 
@@ -12,66 +12,95 @@ jobs:
 
     steps:
     - name: Check commit status
-      id: commit-status
+      id: run script
       run: |
-       Check the status of the Git commit
-       CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-       echo "Current status is: $CURRENT_STATUS"
-       while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
-         do sleep 10; 
-         CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-       done;
-       echo "Current status is: $CURRENT_STATUS"
-       if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
-         then echo "Commit status failed. Canceling execution"; 
-         exit 1; 
-       fi
+        # 1) Assume role for running cloud formation
+        CREDENTIALS=`aws sts assume-role --role-arn "arn:aws:iam::455180012233:role/Github-Actions-Assume-this-Role" --role-session-name AWSCLI-Session --duration-seconds 900 --output=json`
+        # 2) Capture current credentials to reset after executing command
+        export ORIGINAL_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+        export ORIGINAL_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+        aws sts get-caller-identity
+        # 3) Set AWS Assumed Role Credentials on ENV
+        export AWS_DEFAULT_REGION=eu-west-1
+        export AWS_ACCESS_KEY_ID=`echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId'`
+        export AWS_SECRET_ACCESS_KEY=`echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey'`
+        export AWS_SESSION_TOKEN=`echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken'`
+        export AWS_EXPIRATION=`echo ${CREDENTIALS} | jq -r '.Credentials.Expiration'`
+        # 4) Execute command as assumed role
+        aws sts get-caller-identity
+        # 5) Clean up assume role environment variables
+        unset AWS_ACCESS_KEY_ID
+        unset AWS_SECRET_ACCESS_KEY
+        unset AWS_SESSION_TOKEN
+        unset AWS_EXPIRATION
+        # 6) Reset to original credentials
+        export AWS_ACCESS_KEY_ID=${ORIGINAL_AWS_ACCESS_KEY_ID}
+        export AWS_SECRET_ACCESS_KEY=${ORIGINAL_AWS_SECRET_ACCESS_KEY}
+        # 7) Clean up temporary storage
+        unset ORIGINAL_AWS_ACCESS_KEY_ID
+        unset ORIGINAL_AWS_SECRET_ACCESS_KEY
+    
+#     - name: Check commit status
+#       id: commit-status
+#       run: |
+#        Check the status of the Git commit
+#        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+#        echo "Current status is: $CURRENT_STATUS"
+#        while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
+#          do sleep 10; 
+#          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+#        done;
+#        echo "Current status is: $CURRENT_STATUS"
+#        if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
+#          then echo "Commit status failed. Canceling execution"; 
+#          exit 1; 
+#        fi
         
-    - name: Checkout
-      uses: actions/checkout@v1
+#     - name: Checkout
+#       uses: actions/checkout@v1
 
-    - name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-#        role-skip-session-tagging: true
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ap-south-1
-        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
-        role-duration-seconds: 1200
-        role-session-name: MySessionName
+#     - name: Configure AWS Credentials
+#       uses: aws-actions/configure-aws-credentials@v1
+#       with:
+# #        role-skip-session-tagging: true
+#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         aws-region: ap-south-1
+#         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#         role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
+#         role-duration-seconds: 1200
+#         role-session-name: MySessionName
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v1
+#     - name: Login to Amazon ECR
+#       id: login-ecr
+#       uses: aws-actions/amazon-ecr-login@v1
 
-    - name: Build, tag, and push image to Amazon ECR
-      id: build-image
-      env:
-        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        ECR_REPOSITORY: ecs-devops-sandbox-repository
-        IMAGE_TAG: ${{ github.sha }}
-      run: |
-        # Build a docker container and
-        # push it to ECR so that it can
-        # be deployed to ECS.
-        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
-        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+#     - name: Build, tag, and push image to Amazon ECR
+#       id: build-image
+#       env:
+#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#         ECR_REPOSITORY: ecs-devops-sandbox-repository
+#         IMAGE_TAG: ${{ github.sha }}
+#       run: |
+#         # Build a docker container and
+#         # push it to ECR so that it can
+#         # be deployed to ECS.
+#         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+#         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
         
-    - name: Fill in the new image ID in the Amazon ECS task definition
-      id: task-def
-      uses: aws-actions/amazon-ecs-render-task-definition@v1
-      with:
-        task-definition: task-definition.json
-        container-name: ecs-devops-sandbox
-        image: ${{ steps.build-image.outputs.image }}
+#     - name: Fill in the new image ID in the Amazon ECS task definition
+#       id: task-def
+#       uses: aws-actions/amazon-ecs-render-task-definition@v1
+#       with:
+#         task-definition: task-definition.json
+#         container-name: ecs-devops-sandbox
+#         image: ${{ steps.build-image.outputs.image }}
 
-    - name: Deploy Amazon ECS task definition
-      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
-      with:
-        task-definition: ${{ steps.task-def.outputs.task-definition }}
-        service: ecs-devops-sandbox-service
-        cluster: ecs-devops-sandbox-cluster
-        wait-for-service-stability: true
+#     - name: Deploy Amazon ECS task definition
+#       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+#       with:
+#         task-definition: ${{ steps.task-def.outputs.task-definition }}
+#         service: ecs-devops-sandbox-service
+#         cluster: ecs-devops-sandbox-cluster
+#         wait-for-service-stability: true
